# Generated by Django 4.2.1 on 2023-09-13 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='lastbiduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activebids', to=settings.AUTH_USER_MODEL),
        ),
    ]
