# Generated by Django 4.2.1 on 2023-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_lastbiduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='biddatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
